# Synthetic monitors (SIMPLE ping) for every live site.
# Inclusion criteria: >= 20 pageviews in the last 7 days (PageView) AND responding over HTTPS.
# Tenants are checked via the platform healthcheck endpoint; sites without it use the homepage.

locals {
  # Domains exposing /public/healthcheck.ashx (verified 200 OK)
  healthcheck_domains = [
    "1house.globalewallet.com",
    "6star.globalewallet.com",
    "acesse.globalewallet.com",
    "adcom.globalewallet.com",
    "admin.i-payout.com",
    "adx.globalewallet.com",
    "aeu.globalewallet.com",
    "agaralife.globalewallet.com",
    "alovea.globalewallet.com",
    "anovite.globalewallet.com",
    "ardysslife.globalewallet.com",
    "asea.globalewallet.com",
    "asr.globalewallet.com",
    "au.plexus-pay.com",
    "avini.globalewallet.com",
    "beneve.globalewallet.com",
    "bepic.globalewallet.com",
    "bravenly.globalewallet.com",
    "bravenlycanada.globalewallet.com",
    "builderall.globalewallet.com",
    "bwusa.globalewallet.com",
    "bydzyne.globalewallet.com",
    "ca.plexus-pay.com",
    "cardschat.globalewallet.com",
    "clickworker.globalewallet.com",
    "clickworkereu.globalewallet.com",
    "corg.globalewallet.com",
    "covers.globalewallet.com",
    "cp.globalewallet.com",
    "curated.globalewallet.com",
    "dfs.globalewallet.com",
    "engageglobal.globalewallet.com",
    "entre.globalewallet.com",
    "firstfitness.globalewallet.com",
    "fjh.globalewallet.com",
    "frequense.globalewallet.com",
    "gelmoment.globalewallet.com",
    "globallee.globalewallet.com",
    "hba.globalewallet.com",
    "healthyhome.globalewallet.com",
    "healy.globalewallet.com",
    "healyau.globalewallet.com",
    "healyca.globalewallet.com",
    "healyhk.globalewallet.com",
    "healyit.globalewallet.com",
    "healyjp.globalewallet.com",
    "healylatam.globalewallet.com",
    "healysg.globalewallet.com",
    "healyus.globalewallet.com",
    "hyperxarenalv.globalewallet.com",
    "impact.globalewallet.com",
    "incruises.globalewallet.com",
    "jumptohealth.globalewallet.com",
    "kleokolor.globalewallet.com",
    "lactigo.globalewallet.com",
    "legendarymarketer.globalewallet.com",
    "liferegen.globalewallet.com",
    "lifewave.globalewallet.com",
    "limelifeat.globalewallet.com",
    "limelifebyalcone.globalewallet.com",
    "limelifede.globalewallet.com",
    "limelifees.globalewallet.com",
    "limelifeuk.globalewallet.com",
    "liveden.globalewallet.com",
    "livegood.globalewallet.com",
    "mannatechpay.globalewallet.com",
    "masternetworks.globalewallet.com",
    "merchant.globalewallet.com",
    "modexus.globalewallet.com",
    "mpl.globalewallet.com",
    "mtgarena.globalewallet.com",
    "mwrfinancial.globalewallet.com",
    "mwrlife.globalewallet.com",
    "mx.plexus-pay.com",
    "mybiz.globalewallet.com",
    "mydailychoice.globalewallet.com",
    "myopulence.globalewallet.com",
    "neora.globalewallet.com",
    "neumi.globalewallet.com",
    "nhtjp.globalewallet.com",
    "nhtpayca.globalewallet.com",
    "nhtpayus.globalewallet.com",
    "nucleogenex.globalewallet.com",
    "oddspedia.globalewallet.com",
    "onemoreglobal.globalewallet.com",
    "partnerco.globalewallet.com",
    "perfectlyposh.globalewallet.com",
    "pokemon.globalewallet.com",
    "powur.globalewallet.com",
    "provizion.globalewallet.com",
    "pruvitca.globalewallet.com",
    "pruviteu.globalewallet.com",
    "pruvitit.globalewallet.com",
    "pruvitmx.globalewallet.com",
    "pruvitventures.globalewallet.com",
    "resaas.globalewallet.com",
    "retra.globalewallet.com",
    "rimanca.globalewallet.com",
    "rimancl.globalewallet.com",
    "rimanco.globalewallet.com",
    "rimaneu.globalewallet.com",
    "rimanhk.globalewallet.com",
    "rimanitaly.globalewallet.com",
    "rimanmx.globalewallet.com",
    "rimanmy.globalewallet.com",
    "rimanperu.globalewallet.com",
    "rimanph.globalewallet.com",
    "rimanuk.globalewallet.com",
    "rimanus.globalewallet.com",
    "riotapac.globalewallet.com",
    "riotgames.globalewallet.com",
    "saveclub.globalewallet.com",
    "sellabroad.globalewallet.com",
    "shoply.globalewallet.com",
    "shoppyshop.globalewallet.com",
    "smsi.globalewallet.com",
    "snipnutri.globalewallet.com",
    "tgd.globalewallet.com",
    "thegoodinside.globalewallet.com",
    "thesuperaffiliatenetwork.globalewallet.com",
    "three.globalewallet.com",
    "tradera.globalewallet.com",
    "travorium.globalewallet.com",
    "troolife.globalewallet.com",
    "us.plexus-pay.com",
    "velovita.globalewallet.com",
    "viago.globalewallet.com",
    "visiontravel.globalewallet.com",
    "vitalpay.globalewallet.com",
    "wizards.globalewallet.com",
    "worldventures.globalewallet.com",
    "www.globalewallet.com",
    "xosialx.globalewallet.com",
    "zestalnow.globalewallet.com",
  ]

  # Sites without the healthcheck endpoint: monitor the homepage instead
  homepage_domains = [
    "supernova.i-payout.com",
  ]

  synthetic_urls = merge(
    { for d in local.healthcheck_domains : d => "https://${d}/public/healthcheck.ashx" },
    { for d in local.homepage_domains : d => "https://${d}/" },
  )
}

resource "newrelic_synthetics_monitor" "web" {
  for_each = local.synthetic_urls

  account_id = 1468011
  name       = "Web - ${each.key}"
  type       = "SIMPLE"
  status     = "ENABLED"
  period     = "EVERY_10_MINUTES"
  uri        = each.value

  locations_public = ["US_EAST_1", "US_WEST_1"]

  verify_ssl          = true
  bypass_head_request = true
}
